import { ImagePlus, Send, Upload, X } from "lucide-react";
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import type { StoryImage } from "../../../shared/contracts";
import { api } from "../../api/client";

export function EditorPage() {
  const navigate=useNavigate(); const [title,setTitle]=useState(""); const [body,setBody]=useState(""); const [anonymous,setAnonymous]=useState(false); const [images,setImages]=useState<StoryImage[]>([]); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  const upload=async(files:FileList|null)=>{if(!files)return;setBusy(true);setError("");try{for(const file of Array.from(files).slice(0,8-images.length)){const form=new FormData();form.append("file",file);const asset=await api.upload(form) as unknown as StoryImage;setImages(current=>[...current,{...asset,caption:"",order:current.length}]);}}catch(reason){setError((reason as Error).message);}finally{setBusy(false);}};
  const save=async(submit:boolean)=>{setBusy(true);setError("");try{const draft=await api.createStory({title,body,anonymous,images});if(submit)await api.submitStory(draft.storyId);navigate("/account");}catch(reason){setError((reason as Error).message);}finally{setBusy(false);}};
  return <main className="page"><div className="workspace-head"><div><div className="eyebrow">/ SUBMIT AN ANECDOTE</div><h1>写下你的轶事</h1><p>标题和正文必填，图片完全可选。</p></div></div>{error&&<p className="notice">{error}</p>}<div className="form-grid"><section className="panel"><div className="field"><label htmlFor="title">标题</label><input id="title" maxLength={120} value={title} onChange={e=>setTitle(e.target.value)} placeholder="那个夜晚发生了什么？"/></div><div className="field"><label htmlFor="body">正文</label><textarea id="body" maxLength={20000} value={body} onChange={e=>setBody(e.target.value)} placeholder="从你记得最清楚的那一刻开始..."/></div><label className="switch-row"><input type="checkbox" checked={anonymous} onChange={e=>setAnonymous(e.target.checked)}/>公开时隐藏我的 GitHub 身份</label><div className="field" style={{marginTop:18}}><label className="button button--ghost"><ImagePlus size={16}/>添加图片<input hidden type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>upload(e.target.files)}/></label></div><div className="upload-list">{images.map((image,index)=><div className="upload-item" key={image.assetId}><div className="review-meta"><span>图片 {index+1}</span><button className="icon-button" onClick={()=>setImages(items=>items.filter(item=>item.assetId!==image.assetId))}><X size={14}/></button></div><input value={image.caption} placeholder="图片说明（可选）" onChange={e=>setImages(items=>items.map(item=>item.assetId===image.assetId?{...item,caption:e.target.value}:item))}/></div>)}</div><div className="inline-actions" style={{marginTop:20}}><button className="button" disabled={busy||!title.trim()||!body.trim()} onClick={()=>save(false)}><Upload size={15}/>保存草稿</button><button className="button button--accent" disabled={busy||!title.trim()||!body.trim()} onClick={()=>save(true)}><Send size={15}/>提交审核</button></div></section><aside className="panel"><div className="eyebrow">/ PUBLIC PREVIEW</div><h2 className="preview-title">{title||"你的标题会出现在这里"}</h2><p className="preview-body">{body||"正文预览"}</p><div className="review-meta"><span>{anonymous?"匿名投稿":"GitHub 身份公开"}</span><span>{body.length} 字</span></div></aside></div></main>;
}

